server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/buzz_meal_db
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  company.email: funitureoakland@gmail.com


  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - email
              - profile

  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
